# Generated by Django 4.2.4 on 2023-08-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alram',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inquery',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inqueryresponse',
            options={'ordering': ['-id']},
        ),
    ]
