# Generated by Django 4.2.4 on 2023-08-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang_review', '0004_alter_neulhaerangreview_thumbnail_image_and_more'),
        ('neulhajang', '0006_alter_commitmentinnerphotos_inner_photo_and_more'),
        ('neulhaerang', '0009_alter_byeoljji_byeoljji_img_and_more'),
        ('customer_center', '0003_alter_alram_member_alter_inquery_member_and_more'),
    ]

    operations = [

    ]
