# Generated by Django 4.2.4 on 2023-08-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang_review', '0004_alter_neulhaerangreview_thumbnail_image_and_more'),
        ('neulhajang', '0006_alter_commitmentinnerphotos_inner_photo_and_more'),
        ('neulhaerang', '0009_alter_byeoljji_byeoljji_img_and_more'),
        ('customer_center', '0003_alter_alram_member_alter_inquery_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alram',
            name='page_link',
        ),
        migrations.AddField(
            model_name='alram',
            name='neulhaerang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang'),
        ),
        migrations.AddField(
            model_name='alram',
            name='neulhaerang_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AddField(
            model_name='alram',
            name='neulhajang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhajang.neulhajang'),
        ),
    ]
