# Generated by Django 4.2.4 on 2023-08-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_kakao_profile_image'),
        ('customer_center', '0004_remove_alram_page_link_alram_neulhaerang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('isChecked', models.CharField(max_length=30)),
                ('type', models.TextField()),
                ('reference_id', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_alarm',
                'ordering': ['-id'],
            },
        ),
    ]
