# Generated by Django 4.2.4 on 2023-08-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberbadge',
            options={'ordering': ['-id']},
        ),
    ]
