# Generated by Django 4.2.4 on 2023-08-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_member_role_alter_member_member_status'),
        ('static_app', '0003_badge_badge_image_badge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_app.category'),
        ),
        migrations.AlterField(
            model_name='memberbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_app.badge'),
        ),
        migrations.AlterField(
            model_name='memberbadge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
