# Generated by Django 4.2.4 on 2023-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0004_alter_badge_category_alter_memberbadge_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
