# Generated by Django 4.2.4 on 2023-08-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member_email', models.CharField(max_length=200)),
                ('member_nickname', models.CharField(max_length=50)),
                ('member_age', models.IntegerField(default=0)),
                ('member_gender', models.CharField(max_length=10)),
                ('member_role', models.CharField(default='member', max_length=10)),
                ('member_status', models.CharField(default='normal', max_length=10)),
                ('donation_status', models.CharField(default='open', max_length=10)),
                ('total_donation_fund', models.IntegerField(default=0)),
                ('total_donation_count', models.IntegerField(default=0)),
                ('donation_level', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(null=True, upload_to='member/profile/%Y/%m/%d')),
                ('profile_image_choice', models.CharField(default='user', max_length=10)),
            ],
            options={
                'db_table': 'tbl_member',
            },
        ),
    ]
