# Generated by Django 4.2.4 on 2023-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='donation_status',
            field=models.CharField(default='공개', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
