# Generated by Django 4.2.4 on 2023-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_member_role_alter_member_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kakao_profile_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
