# Generated by Django 4.2.4 on 2023-08-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neulhaerang', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeulhaerangReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review_title', models.TextField()),
                ('thumbnail_image', models.ImageField(upload_to='neulhaerang_review/thumbnail')),
                ('byeoljji_receiver_openchat_link', models.TextField()),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_review',
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reply_content', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_review_reply',
            },
        ),
        migrations.CreateModel(
            name='ReviewReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
                ('review_reply', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreviewreply')),
            ],
            options={
                'db_table': 'tbl_review_reply_like',
            },
        ),
        migrations.CreateModel(
            name='ReviewInnerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inner_title_text', models.TextField()),
                ('neulhaerang_content_order', models.IntegerField(default=0)),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_review_inner_title',
            },
        ),
        migrations.CreateModel(
            name='ReviewInnerPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inner_photo', models.ImageField(upload_to='neulharang/inner-photo/')),
                ('neulhaerang_content_order', models.IntegerField(default=0)),
                ('photo_order', models.IntegerField(default=0)),
                ('photo_explanation', models.TextField()),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_review_inner_photos',
            },
        ),
        migrations.CreateModel(
            name='ReviewInnerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inner_content_text', models.TextField()),
                ('neulhaerang_content_order', models.IntegerField(default=0)),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_review_inner_content',
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_type', models.IntegerField(default=0)),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_review_tag',
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_review_like',
            },
        ),
        migrations.CreateModel(
            name='FundUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('history_name', models.TextField()),
                ('history_amount', models.IntegerField(default=0)),
                ('neulhaerang_review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang_review.neulhaerangreview')),
            ],
            options={
                'db_table': 'tbl_fund_usage_history',
            },
        ),
    ]
