# Generated by Django 4.2.4 on 2023-08-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundusagehistory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangreview',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangreviewlike',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangreviewreply',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangreviewtag',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewinnercontent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewinnerphotos',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewinnertitle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reviewreplylike',
            options={'ordering': ['-id']},
        ),
    ]
