# Generated by Django 4.2.4 on 2023-08-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_member_role_alter_member_member_status'),
        ('neulhaerang', '0004_alter_businessplan_neulhaerang_and_more'),
        ('neulhaerang_review', '0002_alter_fundusagehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundusagehistory',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreview',
            name='neulhaerang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreviewlike',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreviewlike',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreviewreply',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreviewreply',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreviewtag',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='reviewinnercontent',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='reviewinnerphotos',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='reviewinnertitle',
            name='neulhaerang_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreview'),
        ),
        migrations.AlterField(
            model_name='reviewreplylike',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='reviewreplylike',
            name='review_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang_review.neulhaerangreviewreply'),
        ),
    ]
