# Generated by Django 4.2.4 on 2023-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(null=True, upload_to='notice/ype'),
        ),
    ]
