# Generated by Django 4.2.4 on 2023-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_notice_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
