# Generated by Django 4.2.4 on 2023-08-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neulhajang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationfeedlike',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='commitmentinnercontent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='commitmentinnerphotos',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='commitmentinnertitle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='innerphoto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajangauthenticationfeed',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajangcommitment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajanginnercontent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajanginnertitle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajanglike',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhajangmission',
            options={'ordering': ['-id']},
        ),
    ]
