# Generated by Django 4.2.4 on 2023-08-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neulhajang', '0002_alter_authenticationfeedlike_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InnerPhoto',
            new_name='NeulhajangInnerPhoto',
        ),
        migrations.AlterModelTable(
            name='neulhajanginnerphoto',
            table='tbl_neulhajang_inner_photo',
        ),
    ]
