# Generated by Django 4.2.4 on 2023-08-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_member_role_alter_member_member_status'),
        ('static_app', '0003_badge_badge_image_badge_category'),
        ('neulhajang', '0003_rename_innerphoto_neulhajanginnerphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationfeedlike',
            name='authentication_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajangauthenticationfeed'),
        ),
        migrations.AlterField(
            model_name='authenticationfeedlike',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='commitmentinnercontent',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='commitmentinnerphotos',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='commitmentinnertitle',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajang',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_app.category'),
        ),
        migrations.AlterField(
            model_name='neulhajang',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='neulhajangauthenticationfeed',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='neulhajangauthenticationfeed',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajangcommitment',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajanginnercontent',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajanginnerphoto',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajanginnertitle',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajanglike',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='neulhajanglike',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
        migrations.AlterField(
            model_name='neulhajangmission',
            name='neulhajang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhajang.neulhajang'),
        ),
    ]
