# Generated by Django 4.2.4 on 2023-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neulhajang', '0005_neulhajang_rejected_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentinnerphotos',
            name='inner_photo',
            field=models.ImageField(upload_to='neulhajang/commitment_innerphoto/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='neulhajang',
            name='thumnail_image',
            field=models.ImageField(upload_to='neulhajang/thumbnail/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='neulhajangauthenticationfeed',
            name='feedPhoto',
            field=models.ImageField(upload_to='neulhajang/feedphoto/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='neulhajanginnerphoto',
            name='inner_photo',
            field=models.ImageField(upload_to='neulhajang/innerphoto/%Y/%m/%d'),
        ),
    ]
