# Generated by Django 4.2.4 on 2023-08-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_app', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Byeoljji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('byeoljji_name', models.CharField(max_length=100)),
                ('byeoljji_img', models.ImageField(null=True, upload_to='neulhaerang/byeoljji/%Y/%m/%d')),
                ('byeoljji_rank', models.IntegerField(default=0)),
                ('byeoljji_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_byeoljji',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Neulhaerang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('fund_duration_start_date', models.DateField(null=True)),
                ('fund_duration_end_date', models.DateField(null=True)),
                ('neulhaerang_duration', models.IntegerField(default=0)),
                ('volunteer_duration_start_date', models.DateField()),
                ('volunteer_duration_end_date', models.DateField()),
                ('participants_max_count', models.IntegerField(default=0)),
                ('target_amount', models.IntegerField(default=0)),
                ('target_amount_alternatives_plan', models.CharField(max_length=1000)),
                ('message_to_admin', models.CharField(max_length=1000)),
                ('neulhaerang_title', models.CharField(max_length=60)),
                ('thumbnail_image', models.ImageField(upload_to='neulhaerang/thumbnail/%Y/%m/%d')),
                ('participants_openchat_link', models.CharField(max_length=500)),
                ('neulhaerang_status', models.CharField(max_length=100)),
                ('rejected_message', models.CharField(max_length=1000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_app.category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_neulhaerang',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('donation_amount', models.IntegerField(default=0)),
                ('donation_content', models.CharField(max_length=500)),
                ('donation_anonymous', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('neulhaerang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_donation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reply_content', models.CharField(max_length=1000)),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerangdonation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('neulhaerang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_reply',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('neulhaerang_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerangreply')),
            ],
            options={
                'db_table': 'tbl_reply_like',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_type', models.IntegerField(default=0)),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_tag',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('neulhaerang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_participants',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('neulhaerang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_like',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangInnerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inner_title_text', models.TextField()),
                ('neulhaerang_content_order', models.IntegerField(default=0)),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_inner_title',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangInnerPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inner_photo', models.ImageField(upload_to='neulhaerang/innerphoto/%Y/%m/%d')),
                ('neulhaerang_content_order', models.IntegerField(default=0)),
                ('photo_order', models.IntegerField(default=0)),
                ('photo_explanation', models.TextField()),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_inner_photos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NeulhaerangInnerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inner_content_text', models.TextField()),
                ('neulhaerang_content_order', models.IntegerField(default=0)),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_inner_content',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberByeoljji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('byeoljji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.byeoljji')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_member_byeoljji',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='byeoljji',
            name='neulhaerang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang'),
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('plan_name', models.TextField()),
                ('plan_amount', models.IntegerField(default=0)),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_business_plan',
                'ordering': ['-id'],
            },
        ),
    ]
