# Generated by Django 4.2.4 on 2023-08-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessplan',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='byeoljji',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='memberbyeoljji',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangdonation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaeranginnercontent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaeranginnerphotos',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaeranginnertitle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangparticipants',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangreply',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='neulhaerangtag',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='replylike',
            options={'ordering': ['-id']},
        ),
    ]
