# Generated by Django 4.2.4 on 2023-08-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_donation_level'),
        ('neulhaerang', '0002_alter_businessplan_options_alter_byeoljji_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neulhaerangreply',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang.neulhaerangdonation'),
        ),
        migrations.CreateModel(
            name='NeulhaerangLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.member')),
                ('neulhaerang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neulhaerang.neulhaerang')),
            ],
            options={
                'db_table': 'tbl_neulhaerang_like',
                'ordering': ['-id'],
            },
        ),
    ]
