# Generated by Django 4.2.4 on 2023-08-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang', '0004_alter_businessplan_neulhaerang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neulhaeranglike',
            name='neulhaerang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang'),
        ),
    ]
