# Generated by Django 4.2.4 on 2023-08-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang', '0005_alter_neulhaeranglike_neulhaerang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberbyeoljji',
            name='neulhaerang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang'),
        ),
        migrations.AlterField(
            model_name='neulhaerangdonation',
            name='neulhaerang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang'),
        ),
        migrations.AlterField(
            model_name='neulhaerangparticipants',
            name='neulhaerang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang'),
        ),
        migrations.AlterField(
            model_name='neulhaerangreply',
            name='neulhaerang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.neulhaerang'),
        ),
    ]
