# Generated by Django 4.2.4 on 2023-08-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang', '0006_alter_memberbyeoljji_neulhaerang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neulhaerang',
            old_name='thumbail_image',
            new_name='thumbnail_image',
        ),
    ]
