# Generated by Django 4.2.4 on 2023-08-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang', '0007_rename_thumbail_image_neulhaerang_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberbyeoljji',
            name='neulhaerang',
        ),
        migrations.AddField(
            model_name='memberbyeoljji',
            name='byeoljji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neulhaerang.byeoljji'),
        ),
        migrations.AlterField(
            model_name='neulhaeranginnerphotos',
            name='inner_photo',
            field=models.ImageField(upload_to='neulhaerang/inner-photo/'),
        ),
    ]
