# Generated by Django 4.2.4 on 2023-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neulhaerang', '0008_remove_memberbyeoljji_neulhaerang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byeoljji',
            name='byeoljji_img',
            field=models.ImageField(null=True, upload_to='neulhaerang/byeoljji/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='neulhaerang',
            name='thumbnail_image',
            field=models.ImageField(upload_to='neulhaerang/thumbnail/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='neulhaeranginnerphotos',
            name='inner_photo',
            field=models.ImageField(upload_to='neulhaerang/innerphoto/%Y/%m/%d'),
        ),
    ]
